# Caipirinha configuration file
caipirinha:
    environment: prod
    port: 23450
    debug: false
    secret: 123456
    servers:
        database_url: mysql+pymysql://root:l3mon@localhost:3306/caipirinha
        redis_url: redis://localhost:6379
    services:
        thorn:
            url: http://localhost:3000
    config:
        SQLALCHEMY_POOL_SIZE: 10
        SQLALCHEMY_POOL_RECYCLE: 240
