limonero:
    port: 23451
    environment: prod
    secret: 123456
    servers:
        database_url: mysql+pymysql://root:l3mon@localhost:3306/limonero
    services:
        thorn:
            url: http://localhost:3000
    config:
        SQLALCHEMY_POOL_SIZE: 0
        SQLALCHEMY_POOL_RECYCLE: 60
