# Stand configuration file

stand:
    environment: prod
    port: 23452
    debug: false
    secret: 123456
    servers:
        database_url: mysql+pymysql://root:l3mon@localhost:3306/stand
        redis_url: redis://localhost:6379
    services:
        tahiti:
            url: http://localhost:23453/tahiti
            auth_token: 123456
        thorn:
            url: http://localhost:3000
    config:
        SQLALCHEMY_POOL_SIZE: 10
        SQLALCHEMY_POOL_RECYCLE: 240
